name: retail-inventory-course
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
      - numpy==1.21.6
      - pandas==1.1.5
      - scipy==1.7.3
      - scikit-learn==1.0.2
      - PyYAML==6.0.1
      - packaging==24.0
      - matplotlib==2.2.3
      - seaborn==0.9.0
      - torch==1.13.1
      - lightgbm==3.3.5
